FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# deps first
COPY hw2/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# app code
COPY hw2/ /app/

EXPOSE 5000
CMD ["python", "app.py"]